sccSizes: sccSizes.ml winsGraph.ml readWinMatrix.ml Makefile
	ocamlc graph.cma winsGraph.ml readWinMatrix.ml sccSizes.ml -o sccSizes

sccPic: sccPic.ml winsGraph.ml readWinMatrix.ml Makefile
	ocamlc graph.cma winsGraph.ml readWinMatrix.ml sccPic.ml -o sccPic

winsGraph: winsGraph.ml Makefile
	ocamlc graph.cma winsGraph.ml -o winsGraph
