recursive-performance.pdf: recursive-performance.tex Makefile
	pdflatex recursive-performance.tex
	pdflatex recursive-performance.tex
	pdflatex recursive-performance.tex
	rm recursive-performance.aux
	rm recursive-performance.log